pipeline {
    agent any

     
    stages {
        stage('Compile and Clean') { 
            steps {

                bat 'mvn compile'
            }
        }
       
	stage('Junit5 Test') { 
            steps {

                bat 'mvn test'
            }
        }

      stage('Jacoco Report'){
        steps{
          jacoco() 
        }
      }

	 stage('SonarQube'){
		steps{
				bat label: '', script: '''mvn sonar:sonar \
				-Dsonar.host.url=http://CDLVDIDEVMAN499:9000 \
				-Dsonar.login=823ea9c071964fd9931e347f90abcbe0f610b8c2'''
			}
   	 }
      
        
          
        stage('Maven Build') { 
            steps {
                bat 'mvn clean install'
            }
        }

		stage('Build Docker image'){
            steps {
              
               
            	 bat 'docker build -t  docker.repository.esi.web.com/clientcentral/training:s2-b2-t3-backend --build-arg VER=1.0 .'
			}
        }
      
       
    

        stage('Docker Push'){
            steps {
                bat 'docker push docker.repository.esi.web.com/clientcentral/training:s2-b2-t3-backend'
            }
        }
        
        stage('Docker deploy'){
            steps {
               
                bat 'docker run -itd -p  8888:8086 docker.repository.esi.web.com/clientcentral/training:s2-b2-t3-backend'
            }
        }
        

        
        
     
    }
}